name: Lifesteal
main: Biswajit\Lifesteal\Main
author: Biswajit
version: 1.2.1
api: 5.0.0
depend:
- Customies
description: You can steal hearts from the players you kill!

commands:
    withdrawal:
        description: "To Withdraw Hearts"
        permission: Lifesteal.cmd.withdrawal

permissions:
    Lifesteal.cmd.withdrawal:
        description: "Permission To Use/Withdraw Command"
        default: true
